name: expocore_invistor2
description: "ExpoCore - Investor Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logo3.png
  fonts:
     - family: Cairo
       fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
    
