// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQB_3hs9Rt2S43MEFYB0dJAuXLJoMxlt8',
    appId: '1:940238627133:web:74975f11ce319a2be7e554',
    messagingSenderId: '940238627133',
    projectId: 'expocore-57f9f',
    authDomain: 'expocore-57f9f.firebaseapp.com',
    databaseURL: 'https://expocore-57f9f-default-rtdb.firebaseio.com',
    storageBucket: 'expocore-57f9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7TBQBXDiXZGFEj9qHj6e2Q6W9GABuuCs',
    appId: '1:940238627133:android:9822115b3e161866e7e554',
    messagingSenderId: '940238627133',
    projectId: 'expocore-57f9f',
    databaseURL: 'https://expocore-57f9f-default-rtdb.firebaseio.com',
    storageBucket: 'expocore-57f9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5snupnaWBULVhJe68I3DDmwg8nyCbY08',
    appId: '1:940238627133:ios:f1c416bf43044ccbe7e554',
    messagingSenderId: '940238627133',
    projectId: 'expocore-57f9f',
    databaseURL: 'https://expocore-57f9f-default-rtdb.firebaseio.com',
    storageBucket: 'expocore-57f9f.firebasestorage.app',
    iosClientId: '940238627133-ah36a7h9jjdf2dmj204ivnapt7gcb5n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.expocoreInvistor2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5snupnaWBULVhJe68I3DDmwg8nyCbY08',
    appId: '1:940238627133:ios:f1c416bf43044ccbe7e554',
    messagingSenderId: '940238627133',
    projectId: 'expocore-57f9f',
    databaseURL: 'https://expocore-57f9f-default-rtdb.firebaseio.com',
    storageBucket: 'expocore-57f9f.firebasestorage.app',
    iosClientId: '940238627133-ah36a7h9jjdf2dmj204ivnapt7gcb5n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.expocoreInvistor2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQB_3hs9Rt2S43MEFYB0dJAuXLJoMxlt8',
    appId: '1:940238627133:web:c0bb4d1ef3e14600e7e554',
    messagingSenderId: '940238627133',
    projectId: 'expocore-57f9f',
    authDomain: 'expocore-57f9f.firebaseapp.com',
    databaseURL: 'https://expocore-57f9f-default-rtdb.firebaseio.com',
    storageBucket: 'expocore-57f9f.firebasestorage.app',
  );
}
